[project]
name = "resume"
version = "0.1.0"
authors = [
    {name = "Jonah Jacobsen"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
